/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "ss_aliases.h"
#include "ss.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "ShiftReg_1.h"
#include "sclk_aliases.h"
#include "sclk.h"
#include "mosi_aliases.h"
#include "mosi.h"
#include "miso_aliases.h"
#include "miso.h"
#include "Clock.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "tick.h"
#include "STEP_aliases.h"
#include "STEP.h"
#include "DIR_aliases.h"
#include "DIR.h"
#include "Direction.h"
#include "ADC_DelSig_1.h"
#include "Clock_3.h"
#include "x_ref_in_aliases.h"
#include "x_ref_in.h"
#include "Step_reg.h"
#include "Timer_1.h"
#include "Microstep.h"
#include "MS1_aliases.h"
#include "MS1.h"
#include "MS2_aliases.h"
#include "MS2.h"
#include "MS3_aliases.h"
#include "MS3.h"
#include "SW1_aliases.h"
#include "SW1.h"
#include "Clock_1.h"
#include "sw1_read.h"
#include "Clock_2.h"
#include "Interrupt_t_aliases.h"
#include "Interrupt_t.h"
#include "StepDir.h"
#include "Clock_4.h"
#include "DIR_IN_aliases.h"
#include "DIR_IN.h"
#include "STEP_IN_aliases.h"
#include "STEP_IN.h"
#include "UART_1_IntClock.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

